---
- name: Tap brew 
  community.general.homebrew_tap:
    name: anchore/syft,anchore/grype
- name: Update cli applications
  community.general.homebrew:
    path: ~/.linuxbrew/bin/brew
    name: 
      - "{{ k9s }}"
      - "{{ yq }}"
      - "{{ jq }}"
      - "{{ k8s }}"
      - stern
      - helm
    state: latest
- name: Update python packages
  pip:
    name: 
      - tern
    state: latest

