---

- name: Install apt components
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - curl
    - make
    - gawk
    - fzf
    - docker.io
    - docker-compose
    - docker-buildx
# install derailed/k9s 
- name: Install k9s
  become: yes
  shell: |
    curl -LsO https://github.com/derailed/k9s/releases/download/{{ k9s }}/k9s_Linux_amd64.tar.gz
    tar -xvzf k9s_Linux_amd64.tar.gz -C /tmp k9s
    chmod a+x /tmp/k9s
    sudo mv /tmp/k9s /usr/local/bin/
    rm k9s_Linux_amd64.tar.gz
  args:
    creates: /usr/local/bin/k9s
# install terraform
- name: Install terraform
  become: yes
  shell: |
    curl -LsO https://releases.hashicorp.com/terraform/{{ terraform }}/terraform_{{ terraform }}_linux_amd64.zip
    unzip terraform_{{ terraform }}_linux_amd64.zip
    chmod a+x terraform
    sudo mv terraform /usr/local/bin/
    rm terraform_{{ terraform }}_linux_amd64.zip
  args:
    creates: /usr/local/bin/terraform
# install kubectl
- name: Install kubectl
  become: yes
  shell: |
    curl -LsO https://storage.googleapis.com/kubernetes-release/release/{{ kubectl }}/bin/linux/amd64/kubectl
    chmod a+x kubectl
    sudo mv kubectl /usr/local/bin/
  args:
    creates: /usr/local/bin/kubectl
# Install databricks cli
- name: Install databricks cli
  become: yes
  shell: |
    curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
# update source path for fzf in bashrc
- name: Update source path for fzf in bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: eval "$(fzf --bash)"
    state: present
    insertafter: EOF
- name: Install fzf completions 
  ansible.builtin.lineinfile:
    path: "/home/{{ remote_user }}/.bashrc"
    line: "[ -f /usr/share/bash-completion/completions/fzf ] && source /usr/share/bash-completion/completions/fzf"
    create: yes

- name: Install fzf keybindings 
  ansible.builtin.lineinfile:
    path: "/home/{{ remote_user }}/.bashrc"
    line: "[ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash"
    create: yes
- name: Create the docker group
  become: yes
  ansible.builtin.group:
    name: docker
    state: present
- name: Add docker group to sudo less
  become: yes
  ansible.builtin.user:
    name: "{{ remote_user }}"
    groups: docker
    append: yes
- name: Install visual studio code
  become: yes
  ansible.builtin.apt:
    name: code
    state: latest
  
