- name: Basic Checks
  hosts: localhost
  tasks:
    - name: Leaving a mark
      command: "touch /tmp/ansible_was_here"
    - name: Current Time
      ansible.builtin.shell: |
        date > /tmp/ansible_was_here
    - name: Register brew binary
      stat:
        path: ~/.linuxbrew/bin/brew1
      register: brew_stat
    - name: Install if brew doesnot exist
      script: test.sh
      when: not brew_stat.stat.exists